######################################################################
##
## Filename: switch_mgr.udo
## Created on: Mon Mar 07 14:38:30 Paris, Madrid 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
